# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/xchapter7x/yup
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make test 
      - run: make build
      - persist_to_workspace:
          root: bin 
          paths:
            - create_new_release.sh 
      - persist_to_workspace:
          root: build 
          paths:
            - hk.exe 
            - hk_osx 
            - hk_unix 
  release:
    docker:
      - image: socialengine/github-release
    working_directory: /go/src/github.com/xchapter7x/yup
    steps:
      - attach_workspace:
          at: bin 
      - attach_workspace:
          at: build 
      - run: ./bin/create_new_release.sh 
workflows:
  version: 2
  build-and-release:
    jobs:
      - build 
      - release:
          requires:
            - build 
